### ISSUE TITLE
Additional data from a session

### ISSUE THREAD

**Issue by baranan** [ProjectImplicit/PIquest#140] opened 2016-09-15 15:28 UTC
The explicit table of most of my datasets from pimanager studies have a few participants with multiple (usually two) rows of the same question. Sometimes, with different responses. As if the participant was able to respond to the same question twice. Further, it also happens with data saved to the explicit table using API.save. So, it is not the user who responded twice, but the task that somehow saved twice, and sometimes with a different value. 

I will follow this message with a few examples from my data, and @andrewdzik will follow up with a similar issue (we suspect it is the same) that was found in James Rae's IAT data. 

To clarify: this is rare. About once in 200-400 sessions.

**Comment by baranan** [comment] 2016-09-18 14:29
Today I started looking at the data of a new study that was launched last Thursday. So far, the data include about 210 participants. 

In the IAT data file (from the IAT table), there was one session with more trials than expected (392 instead of 196). The data is not duplicated. 
That session also had duplicate explicit data (but not the same values, as is clear from the latency values). There was another session with duplicate explicit data. 
The session data of those two sessions don't look unusual. 

I'm attaching the three data files (IAT, explicit, sessions):
[dups.iatatt1.zip](https://github.com/ProjectImplicit/PIquest/files/478760/dups.iatatt1.zip)

User agents of these two sessions is identical:
- Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36
- Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36

The study is here:
https://app-prod-03.implicit.harvard.edu/implicit/showfiles.jsp?user=yba&study=iatatt1

**Comment by eladzlot** [comment] 2016-11-06 15:51
Lets try to get all our clues together here:

**My take on why it is not probable the problem is client side**
We know that sometimes people that have a double record are randomised into different starting conditions. These conditions are sometimes set in JS code that is not part of the player which suggest that the problem is not with the player per-se.
This still leaves an option that the module can be loaded twice by the same page (though this would be a violation of the AMD standard - I wouldn't know how to do it if I wanted to...).

**Is there any chance that we get duplicate records when users refresh the page?**
I gather that duplicate records always require the completion of the first round (@yba?). So that leaves only refreshing on the debriefing page. Also, I don't see why a user would go on to complete an additional questionnaire if they already tried to escape it by refreshing...

**Where else can we look**
So far most of the problems that I've seen happen around midnight for some reason, I would like to check up that option, though there *are* some instances where the problem happens at other times.

**Comment by baranan** [comment] 2016-11-06 17:32
By "first round" do you mean a whole session?  It will be a good clue if it happens only to participants who completed a session. @andrewdzik might have that information. If not, I can look at some recent data.

**Comment by baranan** [comment] 2016-11-06 19:26
I looked at data from the study [yba.ybalab.gss2.0001](https://app-prod-03.implicit.harvard.edu/implicit/showfiles.jsp?user=yba&study=gss2) from the last 7 days. 

These session ids have duplicates in the explicit table:
 9406036 9406926 9406942 9406945 9407230 9408147 9408277 9408394 9408552 9411660 9412103 9413258 9417195 9417603

Some background: This is study has dozens of between-participant conditions (i.e., participants are assigned to very different conditions and starting the study again is not likely to look much similar to the participants).  Because of that, the duplicates are in the explicit data saved from the manager.
It is saved with this code: 
```
		realstart : [{
			inherit:'instructions', name:'realstart', templateUrl: 'intro.jst', title:'Introduction',
			piTemplate:true, header:'Welcome',
			load: function()
			{
            	API.save({
            		domain:global.cat1Label, imageSet:imageSet, 
            		EPITICond:EPITICond, whichPrime : whichPrime, measure:measure
            	});
			}
		}], 
```

The files are zipped here: 
[dups.gss2.zip](https://github.com/ProjectImplicit/PIquest/files/574052/dups.gss2.zip)


Here are the stories of a few of the sessions, as much as I could understand from those files: 
9406036: Dropped out onthe 4th page (the task 'ep'). Did not complete any questionnaire. 

9407230, 9408147, 9406926, 9408394, 9408552, 9412103, 9417195, 9417603: Completed the study. Has data only from one questionnaire. 

9406942: Dropped out on the 4th page (the 5th task_id: 'ep'). Did not complete any questionnaire. The 4th task_id is instructions for a questionnaire, but the 5th task is a different task (the task 'ep'). So, perhaps the session re-started after the 4th task_id, could not save the task_id after the restart, until it reached the 5th task_id (not recorded previously). Then, the particiant decided to drop out.
9408277: Dropped out on the 4th page (the task_id 'amp'). Did not complete any questionnaire. However, the 3th page was instructions to one task (task_id 'instep') but the 4th page was actually a different task (the task_id 'amp'). So, perhaps restarted the study after 'instep' and got all the way to 'amp' until dropped out.

9406945: Dropped out on the 5th page (6th task_id). Completed the questionnaire once.

9411660: Completed the study. **Importantly: this participant completed the questionnaire twice**. This is important because it means that the problem is not some kind of restart of the manager. It is an actual restart of the study. That participant also completed two reaction-time tasks (EP and IAT). So, that participants seems like they completed the study twice (can't know for sure that they reached the debriefing twice).

**Comment by andrewdzik** [comment] 2016-11-07 16:29
I've found the cause of the bug.  From the debriefing page, if you leave the study and then use the back button, you will restart the study.  The browser loads the initial get request for the study entirely from the cache, meaning that the server logic that prevents refreshing the page is never reached since the server is never hit.

I'll work on updating the server code to keep the request from being cached.

**Comment by baranan** [comment] 2016-11-08 09:11
But, what about all the sessions with duplicate data without any indication they reached the debriefing?

**Comment by andrewdzik** [comment] 2016-11-08 12:55
You can leave the study in the middle, press OK, and then use the back
button to restart it also.

**Comment by baranan** [comment] 2016-11-08 13:02
Ah, nice. So, the fix you're proposing is that clicking 'back' will assign the participants to a new study instead of restarting the same study?

**Comment by andrewdzik** [comment] 2016-11-08 13:50
It will send them to the timeout page.  Unless there is a different
behavior that you want.

**Comment by baranan** [comment] 2016-11-08 14:05
In general, when people click Back, an error page is not a great user experience. However, I am not sure that assigning them to a new study is also great because they probably want to return to the same study, which we can't allow them. The error page provides a link to the homepage, and that's probably fine.

**Comment by eladzlot** [comment] 2016-11-08 14:51
Maybe we should replace the error page for timeout/back with an information
page.
It should include an explanation of why the user got there and some common
links back to where they would like to go. (and absolutely no mention of
errors or red text :P).

**Comment by baranan** [comment] 2016-11-08 17:36
Sounds good. @andrewdzik , would it be difficult to implement and deploy with your fix to the bug?

**Comment by eladzlot** [comment] 2016-11-10 10:44
@andrewdzik can we close this?

**Comment by andrewdzik** [comment] 2016-11-10 14:13
Yes, I have the fix working for it.

**Closed** 2016-11-10 14:16 UTC
Labels: bug
